name: 'Attic'
description: 'nix-build with the help of caching to Attic'
author: 'Robin Appelman'
inputs:
  name:
    description: 'Name of a attic cache to push and pull/substitute'
    required: true
  instance:
    description: 'Url of a attic instance to push and pull/substitute'
    required: true
  extraPullNames:
    description: 'Comma-separated list of names for extra attic caches to pull/substitute'
  authToken:
    description: 'Authentication token for Attic, needed for private cache access or to push using an Auth Token'
  skipPush:
    description: 'Set to true to disable pushing build results to the cache'
  pathsToPush:
    description: 'Whitespace-separated list of paths to push. Leave empty to push every build result.'
  pushFilter:
    description: 'Ignored if pathsToPush is set. Regular expression to exclude derivations for the cache push, for example "(-source$|nixpkgs\.tar\.gz$)". Warning: this filter does not guarantee it will not get pushed in case the path is part of the closure of something that will get pushed.'
  atticArgs:
    description: 'Extra command-line arguments to pass to attic. If empty, defaults to -j8'
  installCommand:
    description: 'Override the default attic installation method'
branding:
  color: 'blue'
  icon: 'database'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/main/index.js'
