name: "attic-action test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  public-cache:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: yarn install --frozen-lockfile
    - run: yarn build
    # check if typescript generation was committed
    - run: git diff --exit-code
    - uses: cachix/install-nix-action@v20
    - name: Test public cache
      uses: ./
      with:
        name: attic-action
        instance: https://cache.icewind.me
        authToken: '${{ secrets.ATTIC_TOKEN }}'
    - run: nix-build test.nix

  public-cache-no-key:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: cachix/install-nix-action@v20
    - name: Test public cache no signing key
      uses: ./
      with:
        name: attic-action
        instance: https://cache.icewind.me
    - run: nix-build test.nix

  private-cache:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: cachix/install-nix-action@v20
    - name: Test private cache
      uses: ./
      with:
        name: attic-action-private
        instance: https://cache.icewind.me
        authToken: '${{ secrets.ATTIC_TOKEN }}'
    - run: nix-build test.nix

  nix-master:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v20
      with: 
        nix_path: nixpkgs=channel:nixos-22.11
        install_url: https://nixos-nix-install-tests.cachix.org/serve/kkq45x7yrzvxq8627fi6hkswnfa7mg2l/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - name: Test public cache
      uses: ./
      with:
        name: attic-action
        instance: https://cache.icewind.me
        authToken: '${{ secrets.ATTIC_TOKEN }}'
    - run: nix-build test.nix
